### PR TITLE
Fix for error connecting to Pageant

### PR DESCRIPTION
**Pull request by jaraco**
This is the original patch that fixes paramiko bug #736955, plus an extra revision that adds a comment.

I've used this patch for months now against paramiko, so have confidence in its implementation.

### CODE REVIEW

**Comment by jaraco** [comment]
I've added an additional commit which works around #5. At first blush, this is all that's needed to restore Windows support with PAgeant support.

**Comment by jaraco** [comment]
Is it okay that this pull request addresses two issues? Is there any reason not to accept the pull request? Just let me know if there's anything you want me to do to get this integrated.

**Comment by bitprophet** [comment]
Hey @jaraco -- generally it's best for PRs to be split apart -- the way I've seen it done is to have multiple feature branches in your repo, each with distinct changesets. So you'd have eg `5-fix-fnctl-importerror` with just that import change, and `4-winpageant-support` with that change, and perhaps your `master` includes merges from both so you can test integration.

Then your PRs would target the individual branches and it'd be easier to auto-merge a PR without having to feel like I need to review all the changes within.

EDIT: Don't worry about it for now, though, just keep it in mind for the future :)

**Comment by jaraco** [comment]
Thanks. Yes, I realized it would have been nicer to have the two changes decoupled in that way. I wasn't sure how you would recommend it (separate branches, separate repos, or maybe anonymous branches [mercurial does that; I don't know about git]). Given my relative unfamiliarity with git, and that these issues were relatively small, I was hoping we could handle it as one request. I'll be sure to keep the requests separate in the future.

Thanks!

**Comment by bitprophet** [comment]
Sure :) And I frequently end up cribbing or cherry-picking-then-editing peoples' submissions anyways -- instead of a wholesale merge -- because I'm relatively anal about lots of stuff, and also because it _is_ hard for every committer to package things up perfectly neatly.

I'm about to commit the `fnctl` import problem re #5 and I will try to look at this WinPageant thing next just so we can close both of these issues. It's hard not being able to actually test it myself, but as long as I can run the Fabric test suite with Win-related changes added and it doesn't break...that's good enough ;)

**Comment by bitprophet** [comment]
This has been pushed as 1.7.13.

**Pull request closed without merging**
