### PR TITLE
Python 2.4 compatibility

### PR DESCRIPTION
**Pull request by mcarpenter**
For issue #19

### CODE REVIEW

**Comment by bitprophet** [comment]
I'm afraid we're not interested in supporting Python 2.4 at this point, it's simply too old to be worth the maintenance burden :(  Sorry!

As far as I know, our source project (Paramiko) was supposed to be 2.2/2.3 compatible, so if you don't need any of the tweaks added since we forked, maybe see if Paramiko 1.7.xx still works for you.

**Comment by mcarpenter** [comment]
Perhaps I can rephrase the motivation? ;-)

http://www.python.org/dev/peps/pep-0008/#pet-peeves

"Compound statements (multiple statements on the same line) are generally discouraged."

(I actually came here from paramiko... but I hear what you're saying about py2.4. Might be nice to add this reqt to the README. Thanks!)

**Comment by bitprophet** [comment]
That's not actually what that line refers to, as far as I and others read it. Its syntax happens to be Python 2.5+, but the ternary `true-value if test else false-value` expression _is_ a single statement and in fact _cannot_ be split into multiple lines without making it into an `if/else` or using backslashes.

Actual abuses of "Multiple statements on one line" would be `print x; print y` or possibly `if foo: bar`.

In the case under discussion I think the statement is readable enough; it fits well inside 80 columns and none of the three sub-expressions are very complicated.

(Another correct but less compelling [as it is an appeal to authority] argument is that Guido & co approved adding the ternary statement to Python pretty recently, ergo it must be acceptable to use in some situations over the equivalent `if/else`.)

---

A potential enhancement, however, could be:

```
is_64bit = platform.architecture()[0] == '64bit'
ULONG_PTR = ctypes.c_uint64 if is_64bit else ctypes.c_uint32
```

Which makes the ternary statement even more readable and still only adds 1 extra line instead of 3 ;)

`<insert :bikeshed: emoji here>`

**Comment by kennethreitz** [comment]
:sparkles: :bike: :house: :sparkles:

**Comment by kennethreitz** [comment]
Close enough.

**Pull request closed without merging**
