### PR TITLE
fixes #35

### PR DESCRIPTION
**Pull request by bninja**
support two factor key + password authentication

### CODE REVIEW

**Comment by bitprophet** [comment]
Google tells me this is a super duper new-ish option only available in RHEL6's sshd -- do you know if that's accurate? Would prefer to test this before merging and don't want to waste time downloading an ISO for no reason :) It's not in my CentOS5's 'man sshd_config'.

**Comment by bninja** [comment]
yes that's right: its very new so wont be in anything from centos for quite a while.

we had 2-factor requirement and so installed a patched openssh from source (the auth is controlled by /etc/ssh/sshd_config e.g. RequiredAuthentications2 publickey,password).

im using amazons 2012.03 linux ami (i think its a 5.x, 6 hybrid) so you may be able to patch openssh on something 5.x based to test too.

**Comment by bitprophet** [comment]
>  wont be in anything from centos for quite a while.

God, don't remind me. Bad enough to be on Redhat (not a fan), but to be on the even farther behind copy of Redhat...:sob:

EDIT: Forgot that RHEL/CentOS source from Fedora; Fedora17 has this change and is fortunately available on my primary VPS host. I'll test there.

> seem this code might be clearer if refactored

I'm not too familiar with this part of the codebase (it's a fork of somebody else's code :)) but from what I saw in your diffs, I agree that refactoring could make it more readable.

**Comment by mahmoudimus** [comment]
Hi @bitprophet, please let us know when you've tested this change. We'd like to use your ssh repository rather than use our own to keep up to date with your changes.

**Comment by bitprophet** [comment]
I have a VPS created and plan to test it out this weekend. Will report back here. Thanks again!

**Comment by bitprophet** [comment]
- Tested success/fail via Fabric master + ssh-lib master, e.g. `fab -H <vps IP> -- hostname`
- Pre-merge tests with normal sshd settings:
  - Password: yup
  - Key: yup
- Pre-merge tests with `RequiredAuthentications2 publickey,password`: failed (expected), ssh-lib emits error message `WARNING:ssh.transport:Oops, unhandled type 3`
- Merged
- With `RequiredAuthentications2` still in effect: works with password + key as asserted. :+1:
- With `RequiredAuthentications2` off: still works OK with password, or key, independently.

**Pull request merged**
