### PR TITLE
Add basic support for parameter substitution in SSHConfig.

### PR DESCRIPTION
**Pull request by lndbrg**
In the current form the SSHConfig does not support the substitution variables specified in man ssh_config(5). While support for all of them might not be tremendously usefull, support for the %h in the HostName directive is.

[Editor -- copied desc from #14]

### CODE REVIEW

**Comment by lndbrg** [comment]
There, it should support all parameters now.

**Comment by bitprophet** [comment]
Thanks, I'm a fan of increased compliance with the original spec. Though I don't quite get how `%h` would be useful in `HostName` -- do you have a concrete example? Just curious. I'll merge this soon.

**Comment by lndbrg** [comment]
I use it in our corporate environment. We  have quite long fqdns (and we are missing short dns names between sites) so an ssh to foo-bar-01 matching 'Host foo-*' with 'Hostname %h.foo.bar.baz' will expand to foo-bar-01.foo.bar.baz (which will be added to known_hosts, which i am using for my autocomplete).

**Comment by bitprophet** [comment]
Gotcha, that make sense. Thanks again.

**Pull request merged**
